/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ConferirExtratoRouteImport } from './routes/conferir-extrato'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EntradasRouteImport } from './routes/entradas'
import { Route as FluxoCaixaRouteImport } from './routes/fluxo-caixa'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as PagamentosDiariosRouteImport } from './routes/pagamentos-diarios'
import { Route as PlanoDeContasRouteImport } from './routes/plano-de-contas'
import { Route as PrevistosRouteImport } from './routes/previstos'
import { Route as ProcessosRouteImport } from './routes/processos'
import { Route as RecorrentesRouteImport } from './routes/recorrentes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as RhRouteImport } from './routes/rh'
import { Route as SaidasRouteImport } from './routes/saidas'
import { Route as SaldoDiarioRouteImport } from './routes/saldo-diario'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as FinanceiroAjustesRouteImport } from './routes/financeiro/ajustes'
import { Route as FinanceiroCaixaRouteImport } from './routes/financeiro/caixa'
import { Route as FinanceiroExtratosRouteImport } from './routes/financeiro/extratos'
import { Route as FinanceiroPagamentosRouteImport } from './routes/financeiro/pagamentos'
import { Route as FinanceiroPlanoDeContasRouteImport } from './routes/financeiro/plano-de-contas'
import { Route as FinanceiroReceitasRouteImport } from './routes/financeiro/receitas'
import { Route as FinanceiroRelatoriosRouteImport } from './routes/financeiro/relatorios'
import { Route as GestaoEmpresasRouteImport } from './routes/gestao/empresas'
import { Route as GestaoUsuariosRouteImport } from './routes/gestao/usuarios'
import { Route as RhIndexRouteImport } from './routes/rh/index'
import { Route as RhAtestadosRouteImport } from './routes/rh/atestados'
import { Route as RhConfiguracoesRouteImport } from './routes/rh/configuracoes'
import { Route as RhFolhaRouteImport } from './routes/rh/folha'
import { Route as RhFuncionariosRouteImport } from './routes/rh/funcionarios'
import { Route as RhRecrutamentoRouteImport } from './routes/rh/recrutamento'
import { Route as RhTreinamentoRouteImport } from './routes/rh/treinamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferirExtratoRoute = ConferirExtratoRouteImport.update({
  id: '/conferir-extrato',
  path: '/conferir-extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradasRoute = EntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoCaixaRoute = FluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosDiariosRoute = PagamentosDiariosRouteImport.update({
  id: '/pagamentos-diarios',
  path: '/pagamentos-diarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoDeContasRoute = PlanoDeContasRouteImport.update({
  id: '/plano-de-contas',
  path: '/plano-de-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevistosRoute = PrevistosRouteImport.update({
  id: '/previstos',
  path: '/previstos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessosRoute = ProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorrentesRoute = RecorrentesRouteImport.update({
  id: '/recorrentes',
  path: '/recorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidasRoute = SaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => rootRouteImport,
} as any)
const SaldoDiarioRoute = SaldoDiarioRouteImport.update({
  id: '/saldo-diario',
  path: '/saldo-diario',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroAjustesRoute = FinanceiroAjustesRouteImport.update({
  id: '/financeiro/ajustes',
  path: '/financeiro/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroCaixaRoute = FinanceiroCaixaRouteImport.update({
  id: '/financeiro/caixa',
  path: '/financeiro/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroExtratosRoute = FinanceiroExtratosRouteImport.update({
  id: '/financeiro/extratos',
  path: '/financeiro/extratos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPagamentosRoute = FinanceiroPagamentosRouteImport.update({
  id: '/financeiro/pagamentos',
  path: '/financeiro/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroPlanoDeContasRoute = FinanceiroPlanoDeContasRouteImport.update({
  id: '/financeiro/plano-de-contas',
  path: '/financeiro/plano-de-contas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroReceitasRoute = FinanceiroReceitasRouteImport.update({
  id: '/financeiro/receitas',
  path: '/financeiro/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRelatoriosRoute = FinanceiroRelatoriosRouteImport.update({
  id: '/financeiro/relatorios',
  path: '/financeiro/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoEmpresasRoute = GestaoEmpresasRouteImport.update({
  id: '/gestao/empresas',
  path: '/gestao/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoUsuariosRoute = GestaoUsuariosRouteImport.update({
  id: '/gestao/usuarios',
  path: '/gestao/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhRoute,
} as any)
const RhAtestadosRoute = RhAtestadosRouteImport.update({
  id: '/atestados',
  path: '/atestados',
  getParentRoute: () => RhRoute,
} as any)
const RhConfiguracoesRoute = RhConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => RhRoute,
} as any)
const RhFolhaRoute = RhFolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => RhRoute,
} as any)
const RhFuncionariosRoute = RhFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => RhRoute,
} as any)
const RhRecrutamentoRoute = RhRecrutamentoRouteImport.update({
  id: '/recrutamento',
  path: '/recrutamento',
  getParentRoute: () => RhRoute,
} as any)
const RhTreinamentoRoute = RhTreinamentoRouteImport.update({
  id: '/treinamento',
  path: '/treinamento',
  getParentRoute: () => RhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/conferir-extrato': typeof ConferirExtratoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/empresas': typeof EmpresasRoute
  '/entradas': typeof EntradasRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/orcamento': typeof OrcamentoRoute
  '/pagamentos-diarios': typeof PagamentosDiariosRoute
  '/plano-de-contas': typeof PlanoDeContasRoute
  '/previstos': typeof PrevistosRoute
  '/processos': typeof ProcessosRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao': typeof RevisaoRoute
  '/rh': typeof RhRouteWithChildren
  '/saidas': typeof SaidasRoute
  '/saldo-diario': typeof SaldoDiarioRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/financeiro/ajustes': typeof FinanceiroAjustesRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/extratos': typeof FinanceiroExtratosRoute
  '/financeiro/pagamentos': typeof FinanceiroPagamentosRoute
  '/financeiro/plano-de-contas': typeof FinanceiroPlanoDeContasRoute
  '/financeiro/receitas': typeof FinanceiroReceitasRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
  '/gestao/empresas': typeof GestaoEmpresasRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/rh/atestados': typeof RhAtestadosRoute
  '/rh/configuracoes': typeof RhConfiguracoesRoute
  '/rh/folha': typeof RhFolhaRoute
  '/rh/funcionarios': typeof RhFuncionariosRoute
  '/rh/recrutamento': typeof RhRecrutamentoRoute
  '/rh/treinamento': typeof RhTreinamentoRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/conferir-extrato': typeof ConferirExtratoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/empresas': typeof EmpresasRoute
  '/entradas': typeof EntradasRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/orcamento': typeof OrcamentoRoute
  '/pagamentos-diarios': typeof PagamentosDiariosRoute
  '/plano-de-contas': typeof PlanoDeContasRoute
  '/previstos': typeof PrevistosRoute
  '/processos': typeof ProcessosRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao': typeof RevisaoRoute
  '/saidas': typeof SaidasRoute
  '/saldo-diario': typeof SaldoDiarioRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/financeiro/ajustes': typeof FinanceiroAjustesRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/extratos': typeof FinanceiroExtratosRoute
  '/financeiro/pagamentos': typeof FinanceiroPagamentosRoute
  '/financeiro/plano-de-contas': typeof FinanceiroPlanoDeContasRoute
  '/financeiro/receitas': typeof FinanceiroReceitasRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
  '/gestao/empresas': typeof GestaoEmpresasRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/rh/atestados': typeof RhAtestadosRoute
  '/rh/configuracoes': typeof RhConfiguracoesRoute
  '/rh/folha': typeof RhFolhaRoute
  '/rh/funcionarios': typeof RhFuncionariosRoute
  '/rh/recrutamento': typeof RhRecrutamentoRoute
  '/rh/treinamento': typeof RhTreinamentoRoute
  '/rh': typeof RhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/clientes': typeof ClientesRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/conferir-extrato': typeof ConferirExtratoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/empresas': typeof EmpresasRoute
  '/entradas': typeof EntradasRoute
  '/fluxo-caixa': typeof FluxoCaixaRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/orcamento': typeof OrcamentoRoute
  '/pagamentos-diarios': typeof PagamentosDiariosRoute
  '/plano-de-contas': typeof PlanoDeContasRoute
  '/previstos': typeof PrevistosRoute
  '/processos': typeof ProcessosRoute
  '/recorrentes': typeof RecorrentesRoute
  '/relatorios': typeof RelatoriosRoute
  '/revisao': typeof RevisaoRoute
  '/rh': typeof RhRouteWithChildren
  '/saidas': typeof SaidasRoute
  '/saldo-diario': typeof SaldoDiarioRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/financeiro/ajustes': typeof FinanceiroAjustesRoute
  '/financeiro/caixa': typeof FinanceiroCaixaRoute
  '/financeiro/extratos': typeof FinanceiroExtratosRoute
  '/financeiro/pagamentos': typeof FinanceiroPagamentosRoute
  '/financeiro/plano-de-contas': typeof FinanceiroPlanoDeContasRoute
  '/financeiro/receitas': typeof FinanceiroReceitasRoute
  '/financeiro/relatorios': typeof FinanceiroRelatoriosRoute
  '/gestao/empresas': typeof GestaoEmpresasRoute
  '/gestao/usuarios': typeof GestaoUsuariosRoute
  '/rh/atestados': typeof RhAtestadosRoute
  '/rh/configuracoes': typeof RhConfiguracoesRoute
  '/rh/folha': typeof RhFolhaRoute
  '/rh/funcionarios': typeof RhFuncionariosRoute
  '/rh/recrutamento': typeof RhRecrutamentoRoute
  '/rh/treinamento': typeof RhTreinamentoRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/clientes'
    | '/conciliacao'
    | '/conferir-extrato'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/empresas'
    | '/entradas'
    | '/fluxo-caixa'
    | '/importar'
    | '/login'
    | '/movimentacoes'
    | '/orcamento'
    | '/pagamentos-diarios'
    | '/plano-de-contas'
    | '/previstos'
    | '/processos'
    | '/recorrentes'
    | '/relatorios'
    | '/revisao'
    | '/rh'
    | '/saidas'
    | '/saldo-diario'
    | '/usuarios'
    | '/vendas'
    | '/financeiro/ajustes'
    | '/financeiro/caixa'
    | '/financeiro/extratos'
    | '/financeiro/pagamentos'
    | '/financeiro/plano-de-contas'
    | '/financeiro/receitas'
    | '/financeiro/relatorios'
    | '/gestao/empresas'
    | '/gestao/usuarios'
    | '/rh/atestados'
    | '/rh/configuracoes'
    | '/rh/folha'
    | '/rh/funcionarios'
    | '/rh/recrutamento'
    | '/rh/treinamento'
    | '/rh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/clientes'
    | '/conciliacao'
    | '/conferir-extrato'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/empresas'
    | '/entradas'
    | '/fluxo-caixa'
    | '/importar'
    | '/login'
    | '/movimentacoes'
    | '/orcamento'
    | '/pagamentos-diarios'
    | '/plano-de-contas'
    | '/previstos'
    | '/processos'
    | '/recorrentes'
    | '/relatorios'
    | '/revisao'
    | '/saidas'
    | '/saldo-diario'
    | '/usuarios'
    | '/vendas'
    | '/financeiro/ajustes'
    | '/financeiro/caixa'
    | '/financeiro/extratos'
    | '/financeiro/pagamentos'
    | '/financeiro/plano-de-contas'
    | '/financeiro/receitas'
    | '/financeiro/relatorios'
    | '/gestao/empresas'
    | '/gestao/usuarios'
    | '/rh/atestados'
    | '/rh/configuracoes'
    | '/rh/folha'
    | '/rh/funcionarios'
    | '/rh/recrutamento'
    | '/rh/treinamento'
    | '/rh'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/clientes'
    | '/conciliacao'
    | '/conferir-extrato'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/empresas'
    | '/entradas'
    | '/fluxo-caixa'
    | '/importar'
    | '/login'
    | '/movimentacoes'
    | '/orcamento'
    | '/pagamentos-diarios'
    | '/plano-de-contas'
    | '/previstos'
    | '/processos'
    | '/recorrentes'
    | '/relatorios'
    | '/revisao'
    | '/rh'
    | '/saidas'
    | '/saldo-diario'
    | '/usuarios'
    | '/vendas'
    | '/financeiro/ajustes'
    | '/financeiro/caixa'
    | '/financeiro/extratos'
    | '/financeiro/pagamentos'
    | '/financeiro/plano-de-contas'
    | '/financeiro/receitas'
    | '/financeiro/relatorios'
    | '/gestao/empresas'
    | '/gestao/usuarios'
    | '/rh/atestados'
    | '/rh/configuracoes'
    | '/rh/folha'
    | '/rh/funcionarios'
    | '/rh/recrutamento'
    | '/rh/treinamento'
    | '/rh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  ClientesRoute: typeof ClientesRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ConferirExtratoRoute: typeof ConferirExtratoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  EmpresasRoute: typeof EmpresasRoute
  EntradasRoute: typeof EntradasRoute
  FluxoCaixaRoute: typeof FluxoCaixaRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PagamentosDiariosRoute: typeof PagamentosDiariosRoute
  PlanoDeContasRoute: typeof PlanoDeContasRoute
  PrevistosRoute: typeof PrevistosRoute
  ProcessosRoute: typeof ProcessosRoute
  RecorrentesRoute: typeof RecorrentesRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RevisaoRoute: typeof RevisaoRoute
  RhRoute: typeof RhRouteWithChildren
  SaidasRoute: typeof SaidasRoute
  SaldoDiarioRoute: typeof SaldoDiarioRoute
  UsuariosRoute: typeof UsuariosRoute
  VendasRoute: typeof VendasRoute
  FinanceiroAjustesRoute: typeof FinanceiroAjustesRoute
  FinanceiroCaixaRoute: typeof FinanceiroCaixaRoute
  FinanceiroExtratosRoute: typeof FinanceiroExtratosRoute
  FinanceiroPagamentosRoute: typeof FinanceiroPagamentosRoute
  FinanceiroPlanoDeContasRoute: typeof FinanceiroPlanoDeContasRoute
  FinanceiroReceitasRoute: typeof FinanceiroReceitasRoute
  FinanceiroRelatoriosRoute: typeof FinanceiroRelatoriosRoute
  GestaoEmpresasRoute: typeof GestaoEmpresasRoute
  GestaoUsuariosRoute: typeof GestaoUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferir-extrato': {
      id: '/conferir-extrato'
      path: '/conferir-extrato'
      fullPath: '/conferir-extrato'
      preLoaderRoute: typeof ConferirExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-pagar': {
      id: '/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof ContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entradas': {
      id: '/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof EntradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo-caixa': {
      id: '/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/fluxo-caixa'
      preLoaderRoute: typeof FluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos-diarios': {
      id: '/pagamentos-diarios'
      path: '/pagamentos-diarios'
      fullPath: '/pagamentos-diarios'
      preLoaderRoute: typeof PagamentosDiariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-de-contas': {
      id: '/plano-de-contas'
      path: '/plano-de-contas'
      fullPath: '/plano-de-contas'
      preLoaderRoute: typeof PlanoDeContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previstos': {
      id: '/previstos'
      path: '/previstos'
      fullPath: '/previstos'
      preLoaderRoute: typeof PrevistosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processos': {
      id: '/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof ProcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorrentes': {
      id: '/recorrentes'
      path: '/recorrentes'
      fullPath: '/recorrentes'
      preLoaderRoute: typeof RecorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saidas': {
      id: '/saidas'
      path: '/saidas'
      fullPath: '/saidas'
      preLoaderRoute: typeof SaidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saldo-diario': {
      id: '/saldo-diario'
      path: '/saldo-diario'
      fullPath: '/saldo-diario'
      preLoaderRoute: typeof SaldoDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/ajustes': {
      id: '/financeiro/ajustes'
      path: '/financeiro/ajustes'
      fullPath: '/financeiro/ajustes'
      preLoaderRoute: typeof FinanceiroAjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/caixa': {
      id: '/financeiro/caixa'
      path: '/financeiro/caixa'
      fullPath: '/financeiro/caixa'
      preLoaderRoute: typeof FinanceiroCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/extratos': {
      id: '/financeiro/extratos'
      path: '/financeiro/extratos'
      fullPath: '/financeiro/extratos'
      preLoaderRoute: typeof FinanceiroExtratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/pagamentos': {
      id: '/financeiro/pagamentos'
      path: '/financeiro/pagamentos'
      fullPath: '/financeiro/pagamentos'
      preLoaderRoute: typeof FinanceiroPagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/plano-de-contas': {
      id: '/financeiro/plano-de-contas'
      path: '/financeiro/plano-de-contas'
      fullPath: '/financeiro/plano-de-contas'
      preLoaderRoute: typeof FinanceiroPlanoDeContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/receitas': {
      id: '/financeiro/receitas'
      path: '/financeiro/receitas'
      fullPath: '/financeiro/receitas'
      preLoaderRoute: typeof FinanceiroReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/relatorios': {
      id: '/financeiro/relatorios'
      path: '/financeiro/relatorios'
      fullPath: '/financeiro/relatorios'
      preLoaderRoute: typeof FinanceiroRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/empresas': {
      id: '/gestao/empresas'
      path: '/gestao/empresas'
      fullPath: '/gestao/empresas'
      preLoaderRoute: typeof GestaoEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao/usuarios': {
      id: '/gestao/usuarios'
      path: '/gestao/usuarios'
      fullPath: '/gestao/usuarios'
      preLoaderRoute: typeof GestaoUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh/': {
      id: '/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/atestados': {
      id: '/rh/atestados'
      path: '/atestados'
      fullPath: '/rh/atestados'
      preLoaderRoute: typeof RhAtestadosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/configuracoes': {
      id: '/rh/configuracoes'
      path: '/configuracoes'
      fullPath: '/rh/configuracoes'
      preLoaderRoute: typeof RhConfiguracoesRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/folha': {
      id: '/rh/folha'
      path: '/folha'
      fullPath: '/rh/folha'
      preLoaderRoute: typeof RhFolhaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/funcionarios': {
      id: '/rh/funcionarios'
      path: '/funcionarios'
      fullPath: '/rh/funcionarios'
      preLoaderRoute: typeof RhFuncionariosRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/recrutamento': {
      id: '/rh/recrutamento'
      path: '/recrutamento'
      fullPath: '/rh/recrutamento'
      preLoaderRoute: typeof RhRecrutamentoRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/treinamento': {
      id: '/rh/treinamento'
      path: '/treinamento'
      fullPath: '/rh/treinamento'
      preLoaderRoute: typeof RhTreinamentoRouteImport
      parentRoute: typeof RhRoute
    }
  }
}

interface RhRouteChildren {
  RhAtestadosRoute: typeof RhAtestadosRoute
  RhConfiguracoesRoute: typeof RhConfiguracoesRoute
  RhFolhaRoute: typeof RhFolhaRoute
  RhFuncionariosRoute: typeof RhFuncionariosRoute
  RhRecrutamentoRoute: typeof RhRecrutamentoRoute
  RhTreinamentoRoute: typeof RhTreinamentoRoute
  RhIndexRoute: typeof RhIndexRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhAtestadosRoute: RhAtestadosRoute,
  RhConfiguracoesRoute: RhConfiguracoesRoute,
  RhFolhaRoute: RhFolhaRoute,
  RhFuncionariosRoute: RhFuncionariosRoute,
  RhRecrutamentoRoute: RhRecrutamentoRoute,
  RhTreinamentoRoute: RhTreinamentoRoute,
  RhIndexRoute: RhIndexRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  ClientesRoute: ClientesRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ConferirExtratoRoute: ConferirExtratoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasAPagarRoute: ContasAPagarRoute,
  EmpresasRoute: EmpresasRoute,
  EntradasRoute: EntradasRoute,
  FluxoCaixaRoute: FluxoCaixaRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  OrcamentoRoute: OrcamentoRoute,
  PagamentosDiariosRoute: PagamentosDiariosRoute,
  PlanoDeContasRoute: PlanoDeContasRoute,
  PrevistosRoute: PrevistosRoute,
  ProcessosRoute: ProcessosRoute,
  RecorrentesRoute: RecorrentesRoute,
  RelatoriosRoute: RelatoriosRoute,
  RevisaoRoute: RevisaoRoute,
  RhRoute: RhRouteWithChildren,
  SaidasRoute: SaidasRoute,
  SaldoDiarioRoute: SaldoDiarioRoute,
  UsuariosRoute: UsuariosRoute,
  VendasRoute: VendasRoute,
  FinanceiroAjustesRoute: FinanceiroAjustesRoute,
  FinanceiroCaixaRoute: FinanceiroCaixaRoute,
  FinanceiroExtratosRoute: FinanceiroExtratosRoute,
  FinanceiroPagamentosRoute: FinanceiroPagamentosRoute,
  FinanceiroPlanoDeContasRoute: FinanceiroPlanoDeContasRoute,
  FinanceiroReceitasRoute: FinanceiroReceitasRoute,
  FinanceiroRelatoriosRoute: FinanceiroRelatoriosRoute,
  GestaoEmpresasRoute: GestaoEmpresasRoute,
  GestaoUsuariosRoute: GestaoUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
